# Generated by Django 5.2.12 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="constraints_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="problem",
            name="examples_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="problem",
            name="follow_up",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="problem",
            name="problem_statement",
            field=models.TextField(blank=True, default=""),
        ),
    ]
