from __future__ import annotations

from django.utils.text import slugify


DEFAULT_FOLLOW_UP = "How would you adapt this solution for larger inputs or streaming data?"

DIFFICULTY_PROFILES = {
    "easy": {
        "time_limit_ms": 1000,
        "memory_limit_mb": 128,
        "accepted_count": 24000,
        "submission_count": 27000,
    },
    "medium": {
        "time_limit_ms": 2000,
        "memory_limit_mb": 256,
        "accepted_count": 18000,
        "submission_count": 26000,
    },
    "hard": {
        "time_limit_ms": 3000,
        "memory_limit_mb": 512,
        "accepted_count": 12000,
        "submission_count": 22000,
    },
}


def make_example(example_input: str, example_output: str, explanation: str = "") -> dict:
    return {
        "input": example_input,
        "output": example_output,
        "explanation": explanation,
    }


def make_test_case(
    input_data: str,
    expected_output: str,
    *,
    is_sample: bool,
    is_hidden: bool,
    order: int,
) -> dict:
    return {
        "input_data": input_data,
        "expected_output": expected_output,
        "is_sample": is_sample,
        "is_hidden": is_hidden,
        "order": order,
    }


def build_problem(
    *,
    title: str,
    difficulty: str,
    tags: list[str],
    statement: str,
    sample_input: str,
    sample_output: str,
    hidden_input: str,
    hidden_output: str,
    constraint: str,
    follow_up: str = DEFAULT_FOLLOW_UP,
) -> dict:
    profile = DIFFICULTY_PROFILES[difficulty]

    return {
        "title": title,
        "slug": slugify(title),
        "difficulty": difficulty,
        "tags": list(tags),
        "statement": statement,
        "description": statement,
        "problem_statement": statement,
        "examples": [make_example(sample_input, sample_output, "Sample case")],
        "constraints": [constraint],
        "follow_up": follow_up,
        "time_limit_ms": profile["time_limit_ms"],
        "memory_limit_mb": profile["memory_limit_mb"],
        "accepted_count": profile["accepted_count"],
        "submission_count": profile["submission_count"],
        "is_active": True,
        "test_cases": [
            make_test_case(
                sample_input,
                sample_output,
                is_sample=True,
                is_hidden=False,
                order=1,
            ),
            make_test_case(
                hidden_input,
                hidden_output,
                is_sample=False,
                is_hidden=True,
                order=2,
            ),
        ],
    }


PROBLEM_SEEDS = [
    build_problem(
        title="Two Sum",
        difficulty="easy",
        tags=["arrays", "hash map"],
        statement="Return the indices of the two values that add up to the target.",
        sample_input="nums = [2, 7, 11, 15], target = 9",
        sample_output="[0, 1]",
        hidden_input="nums = [3, 2, 4], target = 6",
        hidden_output="[1, 2]",
        constraint="Each input has exactly one valid answer.",
    ),
    build_problem(
        title="Best Time to Buy and Sell Stock",
        difficulty="easy",
        tags=["arrays", "greedy"],
        statement="Return the maximum profit from one buy and one sell operation.",
        sample_input="prices = [7, 1, 5, 3, 6, 4]",
        sample_output="5",
        hidden_input="prices = [7, 6, 4, 3, 1]",
        hidden_output="0",
        constraint="You may complete at most one transaction.",
    ),
    build_problem(
        title="Maximum Subarray",
        difficulty="easy",
        tags=["arrays", "dynamic programming"],
        statement="Find the contiguous subarray with the largest sum.",
        sample_input="nums = [-2,1,-3,4,-1,2,1,-5,4]",
        sample_output="6",
        hidden_input="nums = [1]",
        hidden_output="1",
        constraint="Subarray must contain at least one number.",
    ),
    build_problem(
        title="Product of Array Except Self",
        difficulty="medium",
        tags=["arrays", "prefix sums"],
        statement="Return an array where each element is the product of every other element.",
        sample_input="nums = [1, 2, 3, 4]",
        sample_output="[24, 12, 8, 6]",
        hidden_input="nums = [1, 2, 0, 4]",
        hidden_output="[0, 0, 8, 0]",
        constraint="Do not use division.",
    ),
    build_problem(
        title="Merge Intervals",
        difficulty="medium",
        tags=["arrays", "intervals"],
        statement="Merge all overlapping intervals and return the condensed list.",
        sample_input="intervals = [[1,3],[2,6],[8,10],[15,18]]",
        sample_output="[[1,6],[8,10],[15,18]]",
        hidden_input="intervals = [[1,4],[4,5]]",
        hidden_output="[[1,5]]",
        constraint="Intervals are inclusive.",
    ),
    build_problem(
        title="Rotate Array",
        difficulty="easy",
        tags=["arrays", "math"],
        statement="Rotate the array to the right by k steps in place.",
        sample_input="nums = [1,2,3,4,5,6,7], k = 3",
        sample_output="[5,6,7,1,2,3,4]",
        hidden_input="nums = [3,99,-1,-100], k = 2",
        hidden_output="[-1,-100,3,99]",
        constraint="Solve with O(1) extra space where possible.",
    ),
    build_problem(
        title="Move Zeroes",
        difficulty="easy",
        tags=["arrays", "two pointers"],
        statement="Move all zero values to the end while preserving the order of non-zero values.",
        sample_input="nums = [0,1,0,3,12]",
        sample_output="[1,3,12,0,0]",
        hidden_input="nums = [4,2,4,0,0,3,0,5,1,0]",
        hidden_output="[4,2,4,3,5,1,0,0,0,0]",
        constraint="Perform the transformation in place.",
    ),
    build_problem(
        title="Longest Consecutive Sequence",
        difficulty="medium",
        tags=["arrays", "hash set"],
        statement="Return the length of the longest sequence of consecutive integers.",
        sample_input="nums = [100,4,200,1,3,2]",
        sample_output="4",
        hidden_input="nums = [0,3,7,2,5,8,4,6,0,1]",
        hidden_output="9",
        constraint="Aim for linear time.",
    ),
    build_problem(
        title="Valid Anagram",
        difficulty="easy",
        tags=["strings", "hash map"],
        statement="Determine whether two strings are anagrams of each other.",
        sample_input='s = "anagram", t = "nagaram"',
        sample_output="true",
        hidden_input='s = "rat", t = "car"',
        hidden_output="false",
        constraint="Strings contain only lowercase letters in the base version.",
    ),
    build_problem(
        title="Group Anagrams",
        difficulty="medium",
        tags=["strings", "hash map"],
        statement="Group words that share the same letter composition.",
        sample_input='strs = ["eat","tea","tan","ate","nat","bat"]',
        sample_output='[["eat","tea","ate"],["tan","nat"],["bat"]]',
        hidden_input='strs = ["","b"]',
        hidden_output='[[""],["b"]]',
        constraint="Preserve grouping, but internal ordering may vary.",
    ),
    build_problem(
        title="Longest Substring Without Repeating Characters",
        difficulty="medium",
        tags=["strings", "sliding window"],
        statement="Return the length of the longest substring with no repeated characters.",
        sample_input='s = "abcabcbb"',
        sample_output="3",
        hidden_input='s = "bbbbb"',
        hidden_output="1",
        constraint="Use a sliding window or equivalent linear-time strategy.",
    ),
    build_problem(
        title="Valid Parentheses",
        difficulty="easy",
        tags=["strings", "stack"],
        statement="Check whether every opening bracket has a matching closing bracket.",
        sample_input='s = "()[]{}"',
        sample_output="true",
        hidden_input='s = "(]"',
        hidden_output="false",
        constraint="Only bracket characters are present in the basic version.",
    ),
    build_problem(
        title="Longest Palindromic Substring",
        difficulty="medium",
        tags=["strings", "two pointers"],
        statement="Return the longest substring that reads the same forward and backward.",
        sample_input='s = "babad"',
        sample_output='"bab"',
        hidden_input='s = "cbbd"',
        hidden_output='"bb"',
        constraint="Return any valid answer if multiple solutions exist.",
    ),
    build_problem(
        title="Palindromic Substrings",
        difficulty="medium",
        tags=["strings", "dynamic programming"],
        statement="Count how many substrings of the input string are palindromes.",
        sample_input='s = "aaa"',
        sample_output="6",
        hidden_input='s = "abc"',
        hidden_output="3",
        constraint="Treat single-character substrings as palindromes.",
    ),
    build_problem(
        title="String to Integer (atoi)",
        difficulty="medium",
        tags=["strings", "parsing"],
        statement="Convert a string into a 32-bit signed integer with standard atoi rules.",
        sample_input='s = "42"',
        sample_output="42",
        hidden_input='s = "   -42"',
        hidden_output="-42",
        constraint="Clamp overflow to the signed 32-bit range.",
    ),
    build_problem(
        title="Implement strStr",
        difficulty="easy",
        tags=["strings", "two pointers"],
        statement="Find the first index where the needle appears in the haystack.",
        sample_input='haystack = "sadbutsad", needle = "sad"',
        sample_output="0",
        hidden_input='haystack = "leetcode", needle = "leeto"',
        hidden_output="-1",
        constraint="Return -1 when the substring does not exist.",
    ),
    build_problem(
        title="Decode String",
        difficulty="medium",
        tags=["strings", "stack"],
        statement="Decode an encoded string such as 3[a2[c]].",
        sample_input='s = "3[a]2[bc]"',
        sample_output='"aaabcbc"',
        hidden_input='s = "3[a2[c]]"',
        hidden_output='"accaccacc"',
        constraint="Nested encodings may appear in the input.",
    ),
    build_problem(
        title="Minimum Window Substring",
        difficulty="hard",
        tags=["strings", "sliding window"],
        statement="Return the smallest substring of s that contains every character in t.",
        sample_input='s = "ADOBECODEBANC", t = "ABC"',
        sample_output='"BANC"',
        hidden_input='s = "a", t = "a"',
        hidden_output='"a"',
        constraint="All matching is case-sensitive.",
    ),
    build_problem(
        title="Reverse Linked List",
        difficulty="easy",
        tags=["linked list", "two pointers"],
        statement="Reverse a singly linked list and return the new head.",
        sample_input="head = [1,2,3,4,5]",
        sample_output="[5,4,3,2,1]",
        hidden_input="head = [1]",
        hidden_output="[1]",
        constraint="The linked list contains at least one node.",
    ),
    build_problem(
        title="Merge Two Sorted Lists",
        difficulty="easy",
        tags=["linked list", "recursion"],
        statement="Merge two sorted linked lists into one sorted list.",
        sample_input="list1 = [1,2,4], list2 = [1,3,4]",
        sample_output="[1,1,2,3,4,4]",
        hidden_input="list1 = [], list2 = [0]",
        hidden_output="[0]",
        constraint="The input lists are already sorted in non-decreasing order.",
    ),
    build_problem(
        title="Linked List Cycle",
        difficulty="easy",
        tags=["linked list", "fast and slow pointers"],
        statement="Determine whether a linked list contains a cycle.",
        sample_input="head = [3,2,0,-4], tail connects to index 1",
        sample_output="true",
        hidden_input="head = [1,2], tail does not connect",
        hidden_output="false",
        constraint="Use constant extra space if possible.",
    ),
    build_problem(
        title="Remove Nth Node From End of List",
        difficulty="medium",
        tags=["linked list", "two pointers"],
        statement="Remove the n-th node from the end of the list and return the head.",
        sample_input="head = [1,2,3,4,5], n = 2",
        sample_output="[1,2,3,5]",
        hidden_input="head = [1], n = 1",
        hidden_output="[]",
        constraint="The list size is at least one.",
    ),
    build_problem(
        title="Reorder List",
        difficulty="medium",
        tags=["linked list", "stack"],
        statement="Reorder the list to follow first, last, second, second-last ordering.",
        sample_input="head = [1,2,3,4]",
        sample_output="[1,4,2,3]",
        hidden_input="head = [1,2,3,4,5]",
        hidden_output="[1,5,2,4,3]",
        constraint="Do not create a new list of values.",
    ),
    build_problem(
        title="Invert Binary Tree",
        difficulty="easy",
        tags=["trees", "recursion"],
        statement="Swap every left and right child in the binary tree.",
        sample_input="root = [4,2,7,1,3,6,9]",
        sample_output="[4,7,2,9,6,3,1]",
        hidden_input="root = [2,1,3]",
        hidden_output="[2,3,1]",
        constraint="The tree can be traversed recursively or iteratively.",
    ),
    build_problem(
        title="Maximum Depth of Binary Tree",
        difficulty="easy",
        tags=["trees", "dfs"],
        statement="Return the number of nodes on the longest path from root to leaf.",
        sample_input="root = [3,9,20,null,null,15,7]",
        sample_output="3",
        hidden_input="root = [1,null,2]",
        hidden_output="2",
        constraint="Null children should be handled explicitly.",
    ),
    build_problem(
        title="Binary Tree Level Order Traversal",
        difficulty="medium",
        tags=["trees", "breadth first search"],
        statement="Return the node values grouped by tree level from top to bottom.",
        sample_input="root = [3,9,20,null,null,15,7]",
        sample_output="[[3],[9,20],[15,7]]",
        hidden_input="root = [1]",
        hidden_output="[[1]]",
        constraint="Traverse the tree level by level.",
    ),
    build_problem(
        title="Diameter of Binary Tree",
        difficulty="easy",
        tags=["trees", "depth first search"],
        statement="Return the length of the longest path between any two nodes.",
        sample_input="root = [1,2,3,4,5]",
        sample_output="3",
        hidden_input="root = [1,2]",
        hidden_output="1",
        constraint="The longest path may or may not pass through the root.",
    ),
    build_problem(
        title="Lowest Common Ancestor of a Binary Tree",
        difficulty="medium",
        tags=["trees", "dfs"],
        statement="Find the lowest common ancestor of two nodes in the tree.",
        sample_input="root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1",
        sample_output="3",
        hidden_input="root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 4",
        hidden_output="5",
        constraint="The tree is not guaranteed to be a binary search tree.",
    ),
    build_problem(
        title="Validate Binary Search Tree",
        difficulty="medium",
        tags=["trees", "binary search tree"],
        statement="Check whether the binary tree satisfies the BST ordering rules.",
        sample_input="root = [2,1,3]",
        sample_output="true",
        hidden_input="root = [5,1,4,null,null,3,6]",
        hidden_output="false",
        constraint="Values in the left subtree must be strictly smaller.",
    ),
    build_problem(
        title="Symmetric Tree",
        difficulty="easy",
        tags=["trees", "recursion"],
        statement="Determine whether the tree is symmetric around its center.",
        sample_input="root = [1,2,2,3,4,4,3]",
        sample_output="true",
        hidden_input="root = [1,2,2,null,3,null,3]",
        hidden_output="false",
        constraint="Compare mirrored subtrees recursively or iteratively.",
    ),
    build_problem(
        title="Kth Smallest Element in a BST",
        difficulty="medium",
        tags=["trees", "binary search tree"],
        statement="Return the k-th smallest value in the BST.",
        sample_input="root = [3,1,4,null,2], k = 1",
        sample_output="1",
        hidden_input="root = [5,3,6,2,4,null,null,1], k = 3",
        hidden_output="3",
        constraint="The tree obeys BST ordering.",
    ),
    build_problem(
        title="Number of Islands",
        difficulty="medium",
        tags=["graphs", "dfs"],
        statement="Count how many disconnected islands of land appear in the grid.",
        sample_input='grid = [["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]',
        sample_output="1",
        hidden_input='grid = [["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]',
        hidden_output="3",
        constraint="Adjacent cells are connected vertically or horizontally only.",
    ),
    build_problem(
        title="Clone Graph",
        difficulty="medium",
        tags=["graphs", "breadth first search"],
        statement="Create a deep copy of an undirected graph.",
        sample_input="graph = [[2,4],[1,3],[2,4],[1,3]]",
        sample_output="[[2,4],[1,3],[2,4],[1,3]]",
        hidden_input="graph = [[2],[1]]",
        hidden_output="[[2],[1]]",
        constraint="The input graph may contain cycles.",
    ),
    build_problem(
        title="Course Schedule",
        difficulty="medium",
        tags=["graphs", "topological sort"],
        statement="Determine whether all courses can be completed given prerequisite pairs.",
        sample_input="numCourses = 2, prerequisites = [[1,0]]",
        sample_output="true",
        hidden_input="numCourses = 2, prerequisites = [[1,0],[0,1]]",
        hidden_output="false",
        constraint="Return false when a dependency cycle exists.",
    ),
    build_problem(
        title="Rotting Oranges",
        difficulty="medium",
        tags=["graphs", "breadth first search"],
        statement="Return the minimum number of minutes until all oranges rot.",
        sample_input="grid = [[2,1,1],[1,1,0],[0,1,1]]",
        sample_output="4",
        hidden_input="grid = [[2,1,1],[0,1,1],[1,0,1]]",
        hidden_output="-1",
        constraint="Return -1 if some fresh orange never rots.",
    ),
    build_problem(
        title="Pacific Atlantic Water Flow",
        difficulty="medium",
        tags=["graphs", "depth first search"],
        statement="Return the cells from which water can flow to both oceans.",
        sample_input="heights = [[1,2,2],[3,2,3],[2,4,5]]",
        sample_output="[[0,2],[1,1],[1,2],[2,0],[2,1],[2,2]]",
        hidden_input="heights = [[2,1],[1,2]]",
        hidden_output="[[0,0],[0,1],[1,0],[1,1]]",
        constraint="Water may flow from higher or equal height to lower or equal height.",
    ),
    build_problem(
        title="Word Ladder",
        difficulty="hard",
        tags=["graphs", "breadth first search"],
        statement="Return the length of the shortest transformation sequence from beginWord to endWord.",
        sample_input='beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log","cog"]',
        sample_output="5",
        hidden_input='beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log"]',
        hidden_output="0",
        constraint="Every transformation must change exactly one character.",
    ),
    build_problem(
        title="Climbing Stairs",
        difficulty="easy",
        tags=["dynamic programming", "fibonacci"],
        statement="Count the number of distinct ways to climb n stairs.",
        sample_input="n = 5",
        sample_output="8",
        hidden_input="n = 6",
        hidden_output="13",
        constraint="You may climb 1 or 2 steps at a time.",
    ),
    build_problem(
        title="House Robber",
        difficulty="medium",
        tags=["dynamic programming", "arrays"],
        statement="Maximize the sum of non-adjacent house values.",
        sample_input="nums = [1,2,3,1]",
        sample_output="4",
        hidden_input="nums = [2,7,9,3,1]",
        hidden_output="12",
        constraint="You cannot rob two adjacent houses.",
    ),
    build_problem(
        title="Coin Change",
        difficulty="medium",
        tags=["dynamic programming", "knapsack"],
        statement="Return the minimum number of coins needed to make the amount.",
        sample_input="coins = [1,2,5], amount = 11",
        sample_output="3",
        hidden_input="coins = [2], amount = 3",
        hidden_output="-1",
        constraint="Return -1 when the amount cannot be formed.",
    ),
    build_problem(
        title="Longest Increasing Subsequence",
        difficulty="medium",
        tags=["dynamic programming", "binary search"],
        statement="Return the length of the longest strictly increasing subsequence.",
        sample_input="nums = [10,9,2,5,3,7,101,18]",
        sample_output="4",
        hidden_input="nums = [0,1,0,3,2,3]",
        hidden_output="4",
        constraint="A subsequence does not need to be contiguous.",
    ),
    build_problem(
        title="Partition Equal Subset Sum",
        difficulty="medium",
        tags=["dynamic programming", "subset sum"],
        statement="Check whether the array can be split into two equal-sum subsets.",
        sample_input="nums = [1,5,11,5]",
        sample_output="true",
        hidden_input="nums = [1,2,3,5]",
        hidden_output="false",
        constraint="All numbers are positive integers.",
    ),
    build_problem(
        title="Unique Paths",
        difficulty="easy",
        tags=["dynamic programming", "combinatorics"],
        statement="Count the number of ways to move from the top-left to bottom-right of a grid.",
        sample_input="m = 3, n = 7",
        sample_output="28",
        hidden_input="m = 3, n = 2",
        hidden_output="3",
        constraint="You can only move right or down.",
    ),
    build_problem(
        title="Edit Distance",
        difficulty="hard",
        tags=["dynamic programming", "strings"],
        statement="Return the minimum number of edits required to transform word1 into word2.",
        sample_input='word1 = "horse", word2 = "ros"',
        sample_output="3",
        hidden_input='word1 = "intention", word2 = "execution"',
        hidden_output="5",
        constraint="Allowed edits are insert, delete, and replace.",
    ),
    build_problem(
        title="Top K Frequent Elements",
        difficulty="medium",
        tags=["heap", "hash map"],
        statement="Return the k most frequent elements in the array.",
        sample_input="nums = [1,1,1,2,2,3], k = 2",
        sample_output="[1,2]",
        hidden_input="nums = [4,1,-1,2,-1,2,3], k = 2",
        hidden_output="[-1,2]",
        constraint="Any order of the top k values is acceptable.",
    ),
    build_problem(
        title="Kth Largest Element in an Array",
        difficulty="medium",
        tags=["heap", "quickselect"],
        statement="Return the k-th largest value in the array.",
        sample_input="nums = [3,2,1,5,6,4], k = 2",
        sample_output="5",
        hidden_input="nums = [3,2,3,1,2,4,5,5,6], k = 4",
        hidden_output="4",
        constraint="Duplicates may appear in the input.",
    ),
    build_problem(
        title="Sliding Window Maximum",
        difficulty="hard",
        tags=["deque", "sliding window"],
        statement="Return the maximum value in each sliding window of size k.",
        sample_input="nums = [1,3,-1,-3,5,3,6,7], k = 3",
        sample_output="[3,3,5,5,6,7]",
        hidden_input="nums = [9,11], k = 2",
        hidden_output="[11]",
        constraint="Optimize beyond the naive nested-loop approach.",
    ),
    build_problem(
        title="Daily Temperatures",
        difficulty="medium",
        tags=["stack", "monotonic stack"],
        statement="For each day, return how many days you must wait for a warmer temperature.",
        sample_input="temperatures = [73,74,75,71,69,72,76,73]",
        sample_output="[1,1,4,2,1,1,0,0]",
        hidden_input="temperatures = [30,40,50,60]",
        hidden_output="[1,1,1,0]",
        constraint="Return 0 when no warmer day exists.",
    ),
    build_problem(
        title="Min Stack",
        difficulty="medium",
        tags=["stack", "design"],
        statement="Design a stack that can return the minimum element in constant time.",
        sample_input='operations = ["push(-2)","push(0)","push(-3)","getMin()"]',
        sample_output='[-3]',
        hidden_input='operations = ["push(1)","push(2)","top()","getMin()"]',
        hidden_output='[2,1]',
        constraint="All primary operations must run in O(1) time.",
    ),
    build_problem(
        title="Subsets",
        difficulty="medium",
        tags=["backtracking", "recursion"],
        statement="Return every possible subset of the input array.",
        sample_input="nums = [1,2,3]",
        sample_output="[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]",
        hidden_input="nums = [0]",
        hidden_output="[[],[0]]",
        constraint="The input array contains distinct integers.",
    ),
]


def iter_problem_slugs(specs: list[dict] | None = None):
    for spec in specs or PROBLEM_SEEDS:
        yield spec["slug"]


def seed_problem_catalog(problem_model, tag_model, problem_tag_model, test_case_model, specs=None):
    specs = specs or PROBLEM_SEEDS
    created = 0
    updated = 0

    for spec in specs:
        problem, was_created = problem_model.objects.update_or_create(
            slug=spec["slug"],
            defaults={
                "title": spec["title"],
                "description": spec["description"],
                "problem_statement": spec["problem_statement"],
                "examples_json": spec["examples"],
                "constraints_json": spec["constraints"],
                "follow_up": spec["follow_up"],
                "difficulty": spec["difficulty"],
                "time_limit_ms": spec["time_limit_ms"],
                "memory_limit_mb": spec["memory_limit_mb"],
                "accepted_count": spec["accepted_count"],
                "submission_count": spec["submission_count"],
                "is_active": spec["is_active"],
            },
        )

        if was_created:
            created += 1
        else:
            updated += 1

        problem_tag_model.objects.filter(problem=problem).delete()
        test_case_model.objects.filter(problem=problem).delete()

        tag_names = []
        for tag_name in spec["tags"]:
            normalized_tag = str(tag_name).strip()
            if normalized_tag and normalized_tag.lower() not in {item.lower() for item in tag_names}:
                tag_names.append(normalized_tag)

        for tag_name in tag_names:
            tag_slug = slugify(tag_name)
            tag, _ = tag_model.objects.get_or_create(
                slug=tag_slug,
                defaults={"name": tag_name},
            )
            if tag.name != tag_name:
                tag.name = tag_name
                tag.save(update_fields=["name"])
            problem_tag_model.objects.get_or_create(problem=problem, tag=tag)

        for test_case in spec["test_cases"]:
            test_case_model.objects.create(problem=problem, **test_case)

    return {
        "created": created,
        "updated": updated,
        "total": len(specs),
    }


def remove_seed_problem_catalog(problem_model, specs=None):
    specs = specs or PROBLEM_SEEDS
    problem_model.objects.filter(slug__in=list(iter_problem_slugs(specs))).delete()
