# Generated by Django 5.2.12 on 2026-04-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_company_user_is_verified_alter_user_role_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
