# Generated by Django 5.2.12 on 2026-04-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
