{{- if not .Values.backend.skip }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "interview-platform.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: {{ .Release.Name }}-backend-sa
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          {{- if .Values.backend.command }}
          command:
{{ toYaml .Values.backend.command | indent 12 }}
          {{- end }}
          {{- if .Values.backend.args }}
          args:
{{ toYaml .Values.backend.args | indent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            {{- range $name, $value := .Values.backend.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /alive/
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 20
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready/
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu | default "250m" }}
              memory: {{ .Values.backend.resources.requests.memory | default "256Mi" }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu | default "1000m" }}
              memory: {{ .Values.backend.resources.limits.memory | default "1024Mi" }}
{{- end }}
