{{- if not .Values.frontend.skip }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "interview-platform.fullname" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
{{- end }}
