apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "interview-platform.fullname" . }}-backend-sa
  labels:
    app: backend
{{- if .Values.backend.serviceAccountRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.backend.serviceAccountRoleArn }}"
{{- end }}
