{{- if not .Values.backend.skip }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-backend-sa
  labels:
    app: backend
{{- if .Values.backend.serviceAccountRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.backend.serviceAccountRoleArn }}"
{{- end }}
{{- end }}
