{{- if not .Values.backend.skip }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "interview-platform.fullname" . }}-backend
spec:
  type: {{ default "ClusterIP" .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
{{- end }}
