apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "interview-platform.fullname" . }}-backend-sm
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
