{{- if not .Values.frontend.skip }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "interview-platform.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
{{- end }}
