apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-servicemonitor
  labels:
    release: prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
