# Generated by Django 5.2.12 on 2026-05-12 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0003_solution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java')], max_length=32)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Runtime Error', 'Runtime Error'), ('Compile Error', 'Compile Error'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Custom Run', 'Custom Run')], default='Pending', max_length=32)),
                ('score', models.PositiveIntegerField(default=0)),
                ('run_mode', models.CharField(choices=[('submit', 'Submit'), ('custom', 'Custom Run')], default='submit', max_length=16)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('actual_output', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.testcase')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='submissions.submission')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
