# Generated by Django 5.2.12 on 2026-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java'), ('go', 'Go')], max_length=32),
        ),
    ]
