replicaCount: 2

backend:
  skip: false
  image: REPLACE_WITH_BACKEND_IMAGE
  port: 8000
  service:
    type: ClusterIP
  env:
    DEBUG: "False"
    SECURE_SSL_REDIRECT: "False"
    ALLOWED_HOSTS: "*"
    CSRF_TRUSTED_ORIGINS: ""
    SECRET_KEY: ""
    DB_NAME: "interview_platform"
    DB_USER: "interview_admin"
    DB_PASSWORD: ""
    DB_HOST: ""
    DB_PORT: "5432"
    REDIS_HOST: ""
    AWS_STORAGE_BUCKET_NAME: ""
    AWS_S3_REGION_NAME: "ap-south-1"
    # Cookie settings to support cross-site frontend requests (set to None and enable Secure with TLS)
    SESSION_COOKIE_SAMESITE: "None"
    CSRF_COOKIE_SAMESITE: "None"
    SESSION_COOKIE_SECURE: "True"
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  serviceAccountRoleArn: ""
  # Optional override for startup command (array) and args for the backend container
  # Default to use daphne (ASGI) because some images may not include gunicorn.
  command: ["daphne"]
  args: ["-b","0.0.0.0","-p","8000","config.asgi:application"]

monitoring:
  serviceMonitor:
    enabled: false

frontend:
  skip: false
  image: REPLACE_WITH_FRONTEND_IMAGE
  port: 80
  service:
    type: LoadBalancer
  # Optional override for startup command (array) and args for the frontend container
  # Example: command: ["daphne"]
  #          args: ["-b","0.0.0.0","-p","80","config.asgi:application"]
  command: []
  args: []

 
